image: gitpod/workspace-full-vnc

tasks:
    - init: |
          git submodule update --init --recursive
    - name: Setup AwesomeWM Config along with necessary dependencies
      before: |
          sudo apt update && sudo apt install awesome xserver-xephyr -y
      init: |
          mkdir -p ~/.config/awesome
      command: |
          for item in /workspace/awesomewm-config/*; do
              ln -sfn "$item" ~/.config/awesome/
          done
    - name: Set bash aliases for easy access of xephyr script
      command: |
          echo "alias start='~/.config/awesome/scripts/xephyr.sh start xephyr && ~/.config/awesome/scripts/xephyr.sh start awesome'" >> ~/.bashrc
          echo "alias stop='~/.config/awesome/scripts/xephyr.sh stop xephyr && ~/.config/awesome/scripts/xephyr.sh stop awesome'" >> ~/.bashrc
          echo "alias quit='~/.config/awesome/scripts/xephyr.sh stop awesome'" >> ~/.bashrc
          echo "alias restart='stop && start'" >> ~/.bashrc

ports:
    - name: VNC
      description: Full GUI Virtual Desktop
      port: 6080
      onOpen: open-browser

vscode:
    extensions:
        - sumneko.lua
        - JohnnyMorganz.stylua
        - castrogusttavo.min-theme
        - castrogusttavo.symbols
        - antfu.icons-carbon
        - gruntfuggly.todo-tree
        - mhutchie.git-graph
        - donjayamanne.githistory
        - timonwong.shellcheck
        - foxundermoon.shell-format
        - tyriar.sort-lines
        - yzhang.markdown-all-in-one
        - davidanson.vscode-markdownlint
        - naumovs.color-highlight
        - oderwat.indent-rainbow
        - tamasfe.even-better-toml
        - idleberg.icon-fonts
        - anseki.vscode-color
        - aaron-bond.better-comments
        - ibm.output-colorizer
        - chouzz.vscode-better-align
        - esbenp.prettier-vscode
